### ISSUE TITLE
Интерактивная игра "Быки и коровы"

### ISSUE THREAD

**Issue by AnatolySAV** [hexlet-codebattle/battle_asserts#1000]
Хочу поделиться с Вами интересной задачей(правда, интерактивной), которую в свое время лет 35 назад успешно, хотя, может быть, не очень красиво и эффективно, реализовал на TurboPascal.
Есть такая игра, у нас её называли «Быки и коровы», суть в том, что двое загадывают по 4-х значному числу без повторяющихся цифр и задача за минимальное число шагов угадать число соперника. Для этого они по очереди обмениваются тестовыми запросами тоже из 4 цифр, а в ответ получают 2 цифры — общее число угаданных цифр и сколько из них стоит на своем месте.
Можно попробовать предложить реализацию этой задачи в списке «Испытаний». Я тоже попробую переписать её с Pascal на Python.
Т.е. программа должна играть за одного из участников - загадать (я делал хитрее) свое число, отвечать на запросы и пытаться угадать число играющего.

**Comment by solar05** [comment]
Привет! Спасибо за предложение, эта задача уже добавлена в платформу https://github.com/hexlet-codebattle/battle_asserts/blob/master/src/battle_asserts/issues/bulls_and_cows.clj
