### ISSUE TITLE
Ошибка в задаче supremum_syracuse

### ISSUE THREAD

**Issue by SKornya** [hexlet-codebattle/battle_asserts#1008]
Элемент последовательности Sk+1 при Sk нечетном, определяется как (3 * Sk + 1) / 2. У вас же он определяется как (3 * Sk + 1).
Пруф, например: https://www.mathnet.ru/links/1253961cb070143f7eca7eac2c4a257a/tvp472.pdf

**Comment by solar05** [comment]
Спасибо, исправлено!
