### ISSUE TITLE
Пустая задача rotate_matrix

### ISSUE THREAD

**Issue by karmaBonfire** [hexlet-codebattle/battle_asserts#1039]
В игре 144163 против бота мне попалась задача rotate_matrix с условием и примерами, но с неправильной сигнатурой (нет входных параметров). Ссылка с предложением законтрибьютить ведёт на несуществующий файл: https://github.com/hexlet-codebattle/battle_asserts/tree/master/src/battle_asserts/issues/rotate_matrix.clj

Ради интереса написал в качестве решения `return []` и система приняла ответ как правильный.

![изображение](https://github.com/hexlet-codebattle/battle_asserts/assets/8749115/b6b00168-197c-4d8c-8654-b22904a328cc)

**Comment by solar05** [comment]
Ага, это кастомная задача, которая через сам codebattle создана, отключил до лучших времен, спасибо!
