### ISSUE TITLE
Проверка ответов в `anagram_finder`

### ISSUE THREAD

**Issue by readyyyk** [hexlet-codebattle/battle_asserts#1067]
Массивы сравниваются странным образом и при одинаковом наполнении массивов, но разной _**сортировке**_ решение отображается со статусом `failure`

## Например:
```js
Receive: [["elad","edla"],["maset","maset"]]
Expected: [["maset","maset"],["elad","edla"]]
Arguments: [["enatooirp","nieln","soup","maset","elad","miws","maset","incetcnnoo","ilimt","edla","tlif"]]
```
![image](https://github.com/hexlet-codebattle/battle_asserts/assets/78100125/9de835f7-a98b-41bd-836f-bbbed1e16c23)

## Но при этом (тоже самое решение):
![image](https://github.com/hexlet-codebattle/battle_asserts/assets/78100125/c812d700-5eb7-4a3f-a2bd-2f27037da635)

## Запись игры:
https://codebattle.hexlet.io/games/165921

<details>
<summary>Итоговый код </summary>
<pre>
const _ = require("lodash");
const R = require("rambda");

const solution = (words) => {
  const eqL = Object.values(words.reduce((acc, cur) => {
    if(!(cur.length in acc)) {
      acc[cur.length] = [cur];
      return acc;
    }
    acc[cur.length].push(cur);
    return acc;
  }, {})).filter(e=>e.length>1);
  
  const res = [];
  eqL.forEach(l=> {
    const ns = l.reduce((a, el)=> {
      if(!(el.split('').sort().join('') in a)) {
        a[el.split('').sort().join('')] = [el];
        return a;
      }
      a[el.split('').sort().join('')].push(el);
      return a;
    },{})
    res.push(...Object.values(ns).filter(el=>el.length>1))
  })

  return res.length ? res : [["anagrams not found!"]];
};

module.exports = solution;
</pre>
</details>

**Comment by readyyyk** [comment]
https://github.com/hexlet-codebattle/battle_asserts/blob/cad5471321f0424fb86b1b0fcff7fecb691139fa/src/battle_asserts/issues/anagram_finder.clj

**Comment by solar05** [comment]
Ага, это особенности проверялки ответов в кодбатле, там порядок важен, уточнил это в описании задачи, спасибо!

**Comment by readyyyk** [comment]
Так а какой должен быть порядок массивов?

@solar05, Вы уточнили только то, что порядок важен, но не сказали какой он должен быть
