### ISSUE TITLE
Task "partiphify.clj" solution does not make sense

### ISSUE THREAD

**Issue by robz-tirtlib** [hexlet-codebattle/battle_asserts#1068]
Task link: https://github.com/hexlet-codebattle/battle_asserts/blob/master/src/battle_asserts/issues/partiphify.clj

According to author's solution, for input data such as [[-11,5],4] correct output is [[-11],[5],[]].
![Screenshot_1](https://github.com/hexlet-codebattle/battle_asserts/assets/62515024/0e46e4f1-4594-4065-ad80-c4180a6cfb97)

It does not make sense, why would we add empty list instead of non-existent third part but wont add one instead of fourth.

**Comment by solar05** [comment]
Yeah, there was a problem with solution, hence, with data generator and examples, fixed in #1069 
Thanks!
