### ISSUE TITLE
Неверное описание задачи subnet_checker и ошибка в тесте #1

### ISSUE THREAD

**Issue by AlexanderRyzhov** [hexlet-codebattle/battle_asserts#1070]
1. Сейчас задача имеет следующую формулировку:
```
  {:en "Create a function, thats check if `subnet` contains in `address`, which contains IPv4 address and subnet mask."
   :ru "Создайте функцию, которая проверяет, входит ли `subnet` в `address`, который содержит IPv4 адрес и маску подсети."})
```
фактически же необходимо проверять, что адрес (`address`) входит в подсеть (`subnet`), а не наооборот, либо, что подсеть **содержит** адрес (в английской версии примерно так и написано, но с ошибками).
Предлагаю изменить формулировку на следующую:
```
  {:en "Create a function, that checks if `subnet` contains `address`. Subnet contains IPv4 address of network and subnet mask."
   :ru "Создайте функцию, которая проверяет, что подсеть (`subnet`) содержит адрес (`address`). Подсеть содержит IPv4 адрес сети и маску подсети."})
```
2.  Если я правильно понял смысл задачи - в качестве входных данных нам передается ip-адрес (строка формата xxx.xxx.xxx.xxx) и адрес подсети, включающий маску подсети (строка формата xxx.xxx.xxx.xxx/xx).
Если так, то тесты не соответствуют сигнатуре функции `const solution = (address, subnet) => {}` (javaScript), т.к. в тестах первым аргументом передается subnet `[{:expected true :arguments ["192.168.100.1/12" "192.168.100.5"]}`
3. Если правильно понял смысл задачи, то для первого теста `[{:expected true :arguments ["192.168.100.1/12" "192.168.100.5"]}` неверно указан ожидаемый результат `true`, т.к. адрес сети, соответствующий указанному адресу и маске 12 это 192.160.0.0.
Если тест корректный - значит я неверно понял условия задачи, тогда и пп.1-2 нуждаются в корректировке.

**Comment by solar05** [comment]
Нет, в задаче ровно так и описано, есть адрес с маской и нужно проверить, что адрес включает в себя переданную вторым аргументом подсеть.
Можно проверить, зайдя в любой ip калькулятор.
Берем пример с 192.168.100.1/12 и 192.168.100.5
 https://shootnick.ru/ip_calc/192.168.100.1/12

И смотрим какие адрес включает в себя подсети, находим 192.168.0.0/14 и делаем вывод, что адреса находятся в одной сети, то есть подсеть входит в переданный адрес.

Можно проверить в другом месте: https://ip-ping.ru/netcalc/ и вводим данные в 4 калькуляторе, где видим, что узлы находятся в одной сети.

**Comment by AlexanderRyzhov** [comment]
Не понимаю.
ip-адрес - это  конкретное число 192.168.100.1 = 192 * 256^3 + 168 * 256^2 +100 * 256^1 + 1 * 256^0
сеть (подсеть) - это диапазон ip-адресов, задаваемый адресом сети и маской подсети. т.е. маска - это характеристика подсети, а не адреса.
Даже если предположить, что исходные данные задаются корректно, то не понятна формулировка как **диапазон** значений адресов может входить конкретное значение адреса. Диапазон может содержать адрес, но не входить в него.

**Comment by AlexanderRyzhov** [comment]
Вот на примере того же калькулятора для третьего тестового примера:
```
   {:expected true
    :arguments ["201.224.121.12/30" "201.224.121.15"]}])
```
https://shootnick.ru/ip_calc/201.224.121.12/30
получим следующие результаты:
**IP адрес сети** = 201.224.121.12
IP адрес первого хоста = 201.224.121.13
IP адрес последнего хоста = 201.224.121.14
**Широковещательный адрес** = 201.224.121.15

Исходя из терминологии в самом калькуляторе - 201.224.121.12 - адрес сети, 201.224.121.15 - максимальный допустимый ip в этой подсети (широковещательный адрес).

т.е. если предположить, что тесткейс правильный, выходит, что первым параметром передается адрес сети + маска, а вторым - адрес, который необходимо проверить на принадлежность к этой сети (вхождени е в эту сеть).

**Comment by solar05** [comment]
> т.е. если предположить, что тесткейс правильный, выходит, что первым параметром передается адрес сети + маска, а вторым - адрес, который необходимо проверить на принадлежность к этой сети (вхождени е в эту сеть).

Да, речь именно про принадлежность адреса. Тогда подправишь формулировку задачи? (надо будет еще название аргументов в решении и сигнатурах тоже изменить)

**Comment by AlexanderRyzhov** [comment]
Ок, попробую поправить формулировки задачи и тесткейсы (в теории если поменять местами параметры в тесткейсах, то они будут соответствовать текущей сигнатуре функции solution). 
Это будет мой первый опыт в опенсорс - я могу ветку прямо в этом репозитории создать - или нужно сначала репо себе форкнуть?

**Comment by solar05** [comment]
Отлично, тогда надо сделать себе форк и потом сделать PR в этот репозиторий
