### ISSUE TITLE
javascript

### ISSUE THREAD

**Issue by rafuck** [hexlet-codebattle/battle_asserts#312]
эта задача разумным образом не решается на javascript, поскольку нам все double, вследствие чего происходит потеря точности

**Comment by MrPhantomT** [comment]
@rafuck О какой задаче идет речь?

**Comment by rafuck** [comment]
Точно не помню
задание наподобие такого:
solution(x) = x + xx + xxx

Смысл в том, чтобы число в строковом представлении конкатенировать с самим
собой, переводить в int и складывать

2016-01-19 16:57 GMT+03:00 MrPhantomT <notifications@github.com>:

> @rafuck <https://github.com/rafuck> О какой задаче идет речь?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hexlet/battle_asserts/issues/312#issuecomment-172860938>
> .
>



-- 
Рафаэль

**Comment by rafuck** [comment]
Вот эта задача
https://github.com/Hexlet/battle_asserts/blob/master/src/battle_asserts/issues/sum_of_exp.clj

**Comment by OlegLustenko** [comment]
Решается это на JavaScript

**Comment by rafuck** [comment]
Конечно решается. Нужно только bigint реализовать. Если набор тестов не поменялся с тех пор, как она мне попадалась.

**Comment by rafuck** [comment]
Более подробно, если угодно.
`
var a = 10000000000000000; // 10^16, требуется 54 бита
console.log(a+1); // 10000000000000000
console.log(a+10); // 10000000000000010
`
Т.е. внутренне переменная в данном случае реализуется через double, а не через long int.

**Comment by OlegLustenko** [comment]
как задача попадется покажу решение, все намного проще

**Comment by rafuck** [comment]
Так прямо тут и покажите. Я редко захожу в игру.
