### ISSUE TITLE
clock_angle does not have a well-defined answer

### ISSUE THREAD

**Issue by Pastafarianist** [hexlet-codebattle/battle_asserts#313]
Checker assumes that something like this is the correct code:

```python
def solution(h, m):
  ang1 = (360.0 / 12) * h + (360.0 / (12 * 60)) * m
  ang2 = (360.0 / 60) * m
  return abs(ang1 - ang2)
```

But it isn't. A better solution is:

```python
def solution(h, m):
  ang1 = (360.0 / 12) * h + (360.0 / (12 * 60)) * m
  ang2 = (360.0 / 60) * m
  return min(abs(ang1 - ang2), abs(ang1 + 360 - ang2))
```

It defines the angle between arrows as the smallest angle among clockwise and counterclockwise directions.

**Comment by justCxx** [comment]
@Pastafarianist спасибо за комментарий.
Данное упрощение было сделано специально, тем более что оно допустимо с точки зрения геометрии - угол в 300 градусов, с другой стороны является углом в 60 градусов.

**Comment by Pastafarianist** [comment]
Даже если так, чекер отвергает вторую программу как выдающую неправильный ответ. Можно это поправить?

**Comment by justCxx** [comment]
В текущей реализации, это технически невозможно. Задания проверятются  генерируемыми юнит тестами, которые требуют однозначных утверждений.
