### ISSUE TITLE
Некорректность задачи sort_elements_by_frequency

### ISSUE THREAD

**Issue by evgenjion** [hexlet-codebattle/battle_asserts#317]
Пытался решить задачу https://github.com/hexlet-codebattle/battle_asserts/blob/master/src/battle_asserts/issues/sort_elements_by_frequency.clj

Проблемы:
1. Очень неочевидный стектрейс – `[ Array(16) ] to deeply equal [ Array(16) ]`
~~2. Если залогировать вывод – кажется все в порядке – `[ 3, 3, 3, 3, 0, 0, 0, 0, 4, 4, 1, 1, -2, -2, 2, -4 ]` (для входных данных `[0,0,3,3,1,-2,3,2,3,1,0,-4,4,0,-2,4]`)~~

**UPD:** Неправильно понял задачу, поэтому понял, в чем проблема, вопрос про стектрейс актуальный.

**Comment by justCxx** [comment]
Очень неочевидный issue)
Стектрейс выдаёт компилятор\интерпретатор того языка на котором вы решаете задачу, кстати вы не уточнили на каком именно.

**Comment by evgenjion** [comment]
Прошу прощения, через какое-то время отформатировал issue, и случайно убрал упоминание про язык:)

Язык JavaScript, да.

Есть возможность в ассертах для JavaScript писать развернутее? Например ``assert(a, b, 'expected result: ' + JSON.stringify(b));``?
