### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by v-kolesnikov** [hexlet-codebattle/battle_asserts#323]
- [x] Выпилить ненужные(?) модули:
  - [x] reader
  - [x] checker
- [x] Ненужные файлы:
  - [ ] issue.example.yml
  - [ ] issue\test не конвертированные из старой версии
- [x] Поправить неймспейсы:
  - [x] выпилить `:include-macros true`
  - [x] выпилить ненужные require
- [x] Обновить зависимости
- [x] Удалить отладочные выводы
- [x] Написать тесты на core
- [x] Поправить Readme.md
  - [x] ссылка на travis

**Comment by solar05** [comment]
Done
