### ISSUE TITLE
Task: complete_string  Шесть битых тестов

### ISSUE THREAD

**Issue by yoba-programmer** [hexlet-codebattle/battle_asserts#399]
Всё хуйня, посоны. Последние шесть тестов -  битые. Бот не проходит, да и я тоже. Такие дела.

Receive: "true"Expected: "false"Arguments: "[rgkljviptafmzynodqbuwecsxhr]"

Receive: "true"Expected: "false"Arguments: "[nmstxewhzfgrlykbvdcqpjouian]"

Receive: "true"Expected: "false"Arguments: "[zyxwrbuliqncfjvetohsdkmpagzyx]"

Receive: "true"Expected: "false"Arguments: "[smcgdqkejxfwuyotznlrpbahivsmc]"

Receive: "true"Expected: "false"Arguments: "[rgkljviptafmzynodqbuwecsxhr]"

Receive: "true"Expected: "false"Arguments: "[nwzdtsfaloeqipvkmryhjxbcgunwzd]"

**Comment by Uunnamed** [comment]
вообще все верно, на этих аргументах ты должен получить false а получаешь true
