### ISSUE TITLE
Automatic test error

### ISSUE THREAD

**Issue by IvanVS140** [hexlet-codebattle/battle_asserts#538]
Battle https://codebattle.hexlet.io/games/19448

There is an error in winner's code:
it is got:
"Whoa, chill out!"  == solution("4?")
instead:
"Sure."  == solution("4?")

But automatic test is passed.

**Comment by solar05** [comment]
Hello! You say about this one test in your link?
![image](https://user-images.githubusercontent.com/38437931/93668460-faea8a00-fa94-11ea-9851-11fdec8d250f.png)

**Comment by IvanVS140** [comment]
Hi!

Hi!
Yes.
Expected		solution("4?") == "Sure."
But receive	solution("4?") == "Whoa, chill out!"

**Comment by imamatory** [comment]
Hi. Battle asserts part is fine. There is issue with code checkers in codebattle repo

**Comment by IvanVS140** [comment]
Yep, i thought so



Отправлено из myMail для iOS


суббота, 19 сентября 2020 г., 18:15 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by ReDBrother** [comment]
Now, we check all test examples for tasks.
