### ISSUE TITLE
"Check" doesn't work at 'join_url_params'

### ISSUE THREAD

**Issue by c1371064** [hexlet-codebattle/battle_asserts#568]
Impossible to get solution evaluation when using Python.
After using the "Check" button it gets stuck in an infinite loop

https://codebattle.hexlet.io/games/19886/
```
from typing import List, Dict

def solution(url: str, params: Dict[str, str]) -> str:
     url = url + "/?"
     keys = sorted(params.keys())
     vals = [params[i] for i in keys]
     sorted_dict = dict(zip(keys,vals))
     for i,v in sorted_dict.items():
          url += str(str(i) +"="+str(v)+"&")
     return url[:-1]
```

**Comment by solar05** [comment]
Hello! There is no error in the issue, I guess, there is a problem in the Python code checking module. Thanks for feedback!

**Comment by ReDBrother** [comment]
I think problem was on arguments generation for solution. I solve it.
