### ISSUE TITLE
Нечестная формулировка задачи в stairway_to_heaven

### ISSUE THREAD

**Issue by aminin** [hexlet-codebattle/battle_asserts#604]
В описании требуется минимизировать "brat ratio".
https://github.com/hexlet-codebattle/battle_asserts/blob/81d279b7e7965f35c0d625082e54723744ef7c1f/src/battle_asserts/issues/stairway_to_heaven.clj#L6-L10

Но, почему в тестах в случае `[9,11,1,5,6,6,5,4,9,12]` ожидается `34`?
Минимальный "brat ratio" в этом случае `30` (достигается при проходе `9, 1, 6, 5, 9`).

Фактически, в коде
https://github.com/hexlet-codebattle/battle_asserts/blob/81d279b7e7965f35c0d625082e54723744ef7c1f/src/battle_asserts/issues/stairway_to_heaven.clj#L33
 **сравниваются только 2 ступени на каждом шаге** (*), что не обеспечивает минимизацию "brat ratio" за проход.

Если явно указать на этот факт (*), то сложность задачи будет `easy`.

Расхождение условия задачи и тестов поднимает её сложность до `hard` и превращает решение из построения алгоритма в поиск ошибки в условии (путём анализа исходника на гитхабе).

**Comment by solar05** [comment]
Привет! Спасибо за фидбек! В задаче немного некорректно описано, а конкретно тут:
> returns the minimum brat index

Так как предполагается, что изначальные индексы в массиве неизвестны, как и сам размер массива, то требуется создать минимизирующую функцию, поэтому следуя такой логике, приведенный пример будет обходиться в таком порядке `[9, 1, 5, 6, 4, 9]`, отсюда и получается 34. То есть решение не должно находить глобальный минимум, а выбирать локальный минимум на каждой итерации.

**Comment by aminin** [comment]
Привет, @solar05!

Основная проблема в том, что в описании задачи ничего явно не указывает на (*).

**Подбор слов** (типа `brat index`) -- тоже проблема, но она скорее затрудняет восприятие, чем напрямую искажает смысл.

**Comment by aminin** [comment]
## Подбор слов

Слова `index`, `number`, `ratio` -- это всё "какое-то число по-английски".
Однако, у каждого из этих слов есть своё отдельное значение и контекст применения.

 * Index -- указатель. В одном тексте со словом **массив**, index -- номер элемента в массиве, начиная с 0.
 * Ratio -- отношение. Это когда что-то на что-то поделили `Ratio = A / B`
 * Number -- просто число (любое).

Беспорядочное использование этих слов вынуждает читателя спотыкаться и заменять их на `какое-то число`.

**Comment by aminin** [comment]
## Синонимизация

Почему в одном случае `brat ratio` а в другом `brat index`?
Сам по себе `brat ratio` -- авторский термин (брат какое-то число), а вместе с `brat index` (брат какое-то другое число) -- это уже два авторских термина, которые заставляют задуматься: Это одно и тоже или разные "какие-то числа"?

Я понимаю, что автор русский и привык чередовать слова "Печорин", "главный герой", "протагони́ст" и "он", но нерусские могут об этом не догадаться.

**Comment by solar05** [comment]
Поправил описание в #609 , надеюсь теперь описание задачи понятнее!
