### ISSUE TITLE
Fix or refactor disabled tasks

### ISSUE THREAD

**Issue by solar05** [hexlet-codebattle/battle_asserts#853]
There are some disabled tasks, that needs to be fixed or refactored.
Disabled tasks list: `all_symmetric_pairs, build_key_value, celsius_to_fahrenheit, counting_words, flatten, fridge_fun, parse_post_form_params, remove_duplicates, rotate_sequence, sea_battle, straight_line_equation, vasya_and_sword`.

**Comment by vtm9** [comment]
@michellymenezes you can also just create your own new tasks, and then play them on codebattle.hexlet.io
