### ISSUE TITLE
Задачки

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/battle_asserts#860]
Написать метод/функцию, который/которая на вход принимает число (float), а на выходе получает число, округленное до пятерок.
Пример:
27 => 25, 27.8 => 30, 41.7 => 40.

Написать метод/функцию, который/которая на вход принимает число (int), а на выходе выдает слово “компьютер” в падеже, соответствующем указанному количеству. Например, «25 компьютеров», «41 компьютер», «1048 компьютеров».

**Comment by solar05** [comment]
Со второй задачкой не совсем уверен, что подходящий формат, так как основной упор идет на английский язык, но в нем история со множественным числом немного запутанная, поэтому предлагаю переформулировать вторую задачу на упрощенный английский вариант (без рассмотрения слов исключений).

**Comment by fey** [comment]
@solar05 
"Написать метод/функцию, который/которая на вход принимает число (int), а на выходе выдает слово в множественном или единственном числе (только простые случаи), соответствующем указанному количеству. Например, «25 компьютеров», «41 компьютер», «1048 компьютеров»."

м?
