### ISSUE TITLE
Задачка

### ISSUE THREAD

**Issue by yulia633** [hexlet-codebattle/battle_asserts#884]
Напишите метод, который принимает на вход строку и меняет порядок букв в каждом слове на обратный с сохранением регистра и пунктуации.

Например:

revertCharacters("Привет! Давно не виделись.");
echo $result; // Тевирп! Онвад ен ьсиледив.

```
["Тевирп! Онвад ен ьсиледив.", "Привет! Давно не виделись."],
[" ", " "],
["Olleh! Era uoy.", "Hello! Are you."],
["DlrowolleH11!", "11Helloworld!"],
```

**Comment by sgmdlt** [comment]
к сожалению почти такое уже
[есть](https://github.com/hexlet-codebattle/battle_asserts/blob/b47d6dec027eb0d43c29a1782081830e0e57fec8/src/battle_asserts/issues/mangling_sentence.clj)

**Comment by solar05** [comment]
На самом деле, выглядит как кандидат на задачку с уровнем сложности `elementary` или `easy` , в задаче, которую упомянули, слова все же сортируются, а не переворачиваются, к тому же у нас есть схожие задачи, так что спасибо за предложение!
