### ISSUE TITLE
Неверное описание задачи

### ISSUE THREAD

**Issue by Semigradsky** [hexlet-codebattle/battle_asserts#897]
https://codebattle.hexlet.io/games/59654

В описании сказано, что нужно найти количество уникальных положительных и отрицательных чисел, но фактически нужно найти просто количество положительных и отрицательных чисел, не зависимо от их уникальности в массиве.

**Comment by sgmdlt** [comment]
Салют. 

С описанием все верно. Проблема была в генерируемых данных -- числа выбирались из слишком большого диапазона, и в итоговом массиве повторения почти не встречались.

Уменьшил диапазон, теперь решения без учета уникальности не пройдут.

Спасибо за ишью! Присылайте еще.

**Comment by Semigradsky** [comment]
@sgmdlt тогда здесь: `{:expected true :arguments [[1 1 2 2 3 3 4 -4]]}` должно быть не `true`, а `false`:
уникальных положительных чисел - 1
уникальных отрицательных чисел - 1

Выходит и `solution` не верный, если такой тест проходит.

**Comment by sgmdlt** [comment]
Тут все значительно проще. Это задание уровня elementary, и тут просто спрашивается, каких чисел больше после удаления дубликатов.
Уберу это `{:expected true :arguments [[1 1 2 2 3 3 4 -4]]}` из примеров и подумаю как перефразировать, чтобы избежать разночтения.

**Comment by solar05** [comment]
Fixed in #898 
Thanks for issue!

**Comment by Semigradsky** [comment]
@sgmdlt не понятно почему теперь `{:expected true :arguments [[1 1 2 2 3 3 -4 -4]]}`? Ведь уникальных положительных не больше, чем уникальных отрицательных.

**Comment by sgmdlt** [comment]
[1 1 2 2 3 3 -4 -4]
- > убираем дубликаты
[1 2 3 -4]
-> считаем положительные
3
-> считаем отрицательные
1
-> 3 > 1
true ✌️

**Comment by Semigradsky** [comment]
А, не заметил, что описание задачи изменилось, спасибо)

Жалко, конечно, что вылетел из турнира из-за этой задачи.
