### ISSUE TITLE
reverse_with_capitalize - сделать попроще или изменить уровень сложности

### ISSUE THREAD

**Issue by fey** [hexlet-codebattle/battle_asserts#900]
https://github.com/hexlet-codebattle/battle_asserts/blob/master/src/battle_asserts/issues/reverse_with_capitalize.clj

Сейчас в задачке, Если в середине строки есть символы !. и тд, то нужно использовать регулярку, что сильно усложняет решение. Предлагаю подставлять в тесты обычные предложения (без запятых и тд), либо переворачивать все слова (с символами).

**Comment by sgmdlt** [comment]
Салют

Вроде не обязательно использовать регулярку (в решении ее и нет).
Но наверно стоит перебрать задачки уровня easy и переместить в medium те, что потребуют дольше времени, чем дается на турнирах.

**Comment by fey** [comment]
Ага, как раз из-за символов в середине нужно дописывать доп функции. Ну и имя параметра sentence как бы намекает (что это предложение)
