### ISSUE TITLE
Некорректные тесты задания sudoku_checker

### ISSUE THREAD

**Issue by IoannP** [hexlet-codebattle/battle_asserts#959]
В каждой из колонок повторяются числа и должно ожидаться false, a ожидается true.
[заданиe](https://github.com/hexlet-codebattle/battle_asserts/blob/master/src/battle_asserts/issues/sudoku_checker.clj)
![image](https://user-images.githubusercontent.com/51704301/177000574-1924e7b3-ff4c-425c-af46-44603a8ebfec.png)

**Comment by solar05** [comment]
Отключили пока
