### ISSUE TITLE
Скорректировать условие задачи

### ISSUE THREAD

**Issue by evgeniyworkbel** [hexlet-codebattle/battle_asserts#968]
![image](https://user-images.githubusercontent.com/93836126/183256875-33777950-10d9-4c55-9b83-e2d282bdf8b2.png)

Фраза "в указанном порядке" вводит в заблуждение. К примеру, я подумал, что требуется найти мин и макс и вывести их том порядке, в которой они встречаются в заданном массиве.

Лучше убрать эту фразу.

**Comment by solar05** [comment]
Fixed, thanks!
