### ISSUE TITLE
Incorrect "pythagorean_triple" task example

### ISSUE THREAD

**Issue by IgorGakhov** [hexlet-codebattle/battle_asserts#975]
**Ошибка примера в задании [pythagorean_triple](https://codebattle.hexlet.io/tasks/98):**

`true  == solution([3,5,4])` некорректен для x^2 + y^2 = z^2. Четверку и пятерку нужно поменять местами.

Что странно, на каком то этапе [пример уже был в нужном порядке](https://github.com/hexlet-codebattle/battle_asserts/commit/e481ae318651c87b3fc2a17d8b58d3e7547cd4a8), но был изменен.

**Comment by IgorGakhov** [comment]
PR: https://github.com/hexlet-codebattle/battle_asserts/pull/976

**Comment by vtm9** [comment]
Так, секундочку. Чем треугольник 3,4,5 отличается от 3,5,4?! Все там хорошо в задаче. Возможно твоя программа рассчитывает, что гипотенуза придет третьей, но она не обязана приходить третьей.

**Comment by IgorGakhov** [comment]
Да, расчет был из прихода гипотенузы третьим элементом. Если порядок неважен, то в таком случае, по моему мнению, нужно это явно указать в описании задания.

**Comment by IgorGakhov** [comment]
Я даже зная, что порядок был изменен, не догадался до этого. Прошу прощения тогда.

**Comment by vtm9** [comment]
В этом и смысл задачки. Она очень простая, но догадаться что надо отсортировать по длине часть решения

**Comment by vtm9** [comment]
пример как раз косвенно на это показывал)

**Comment by solar05** [comment]
Можно задачке тогда еще соответствующий тег добавить!
