### ISSUE TITLE
Создать механизм обжалования решения соперника

### ISSUE THREAD

**Issue by IgorGakhov** [hexlet-codebattle/battle_asserts#977]
Соперник выиграл игру [partiphify](https://codebattle.hexlet.io/tasks/6336782) с таким решением:

```Python
class U(int):
    def __init__(self): ...
    def __eq__(self, other): return True

def solution(number):
    return U()
```

Суть в том что он переприсвоил метод сравнения, нагло обманув тесты. В контексте одной игры это конечно ерунда, но судя по тому, что у него очень высокий рейтинг - он прибегает к грязным методам регулярно.

Думаю не помешает кнопка репорта на такие случаи, чтобы исключить подобные прецеденты и сделать комьюнити чище.

**Comment by vtm9** [comment]
О, спасибо, хорошая идея. Думаю мы так сделаем. В целом чтобы так нельзя было делать, мы поменяли формат проверки, до питона еще не дошли

**Comment by vtm9** [comment]
костыль с Питоном пофиксили
