### ISSUE TITLE
Задание "split_names" не работает

### ISSUE THREAD

**Issue by odhako** [hexlet-codebattle/battle_asserts#979]
https://github.com/hexlet-codebattle/battle_asserts/blob/master/src/battle_asserts/issues/split_names.clj
https://codebattle.hexlet.io/games/95208

Не принимает как мое решение так и решение бота.
```
Receive: [{"first":"Harold","last":"Abelson"},{"first":"Julie","last":"Sussman"}]
Expected: [{"first":"Harold","last":"Abelson"},{"first":"Julie","last":"Sussman"}]
Arguments: [["Harold Abelson","Julie Sussman"]]
```

**Comment by vtm9** [comment]
мы немного шатали прод в это время
сейчас все должно работать, сорри
