### ISSUE TITLE
Не проходит решение.

### ISSUE THREAD

**Issue by antonkrupin** [hexlet-codebattle/battle_asserts#982]
Не понятно, почему решение не проходит. Бот столкнулся так же с этой проблемой.
![задача_скрин_1](https://user-images.githubusercontent.com/18227707/188868113-6b89f4e9-0326-49d6-8867-1405765d0e90.jpg)
![задача_скрин_2](https://user-images.githubusercontent.com/18227707/188868127-e5d6b939-cf16-488a-9bea-02dca2df4e9c.jpg)

**Comment by ReDBrother** [comment]
Мы ее вроде пофиксили)
