### ISSUE TITLE
Добавить в описание решения, как считается 0

### ISSUE THREAD

**Issue by kaziamov** [hexlet-codebattle/battle_asserts#995]
Не все знают, относится ли 0 к положительным или отрицательным числам (я например не знал)

**Comment by ReDBrother** [comment]
@kaziamov Привет! О какой задаче речь?

**Comment by kaziamov** [comment]
positive_dominant

*Сорри, не заметил, что репозиторий на все задачи, а не на одну ))

**Comment by solar05** [comment]
Оставил небольшое уточнение в задаче, чтобы напрямую не подсказывать :)
